# GraphQL schema example
#
# https://gqlgen.com/getting-started/

scalar Role
scalar Time

type Instance {
  id: ID!
  name: String!
  URL: String!
}

type Event {
  id: ID!
  instance: Instance!
  eventInfo: EventInfo!
  starts: Time!
  ends: Time
}

type EventInfo {
  title: String!
  slug: String!
  locationName: String!
  locationURL: String!
}

type Workshop {
  id: ID!
  instance: ID!
  workshopInfo: WorkshopInfo!
  starts: Time!
  ends: Time
  event: Event!
}

type WorkshopInfo {
  title: String!
  slug: String!
  locationName: String!
  locationURL: String!
  couples: Boolean!
}

input WorkshopInfoInput {
  title: String!
  slug: String!
  locationName: String!
  locationURL: String!
  couples: Boolean!
}

input WorkshopInput {
  id: ID!
  instance: ID!
  workshopInfo: WorkshopInfoInput!
  starts: Time!
  ends: Time
  eventID: ID!
}

type Query {
  workshops: [Workshop!]!
}

type Mutation {
  createWorkshop(input: WorkshopInput!): Workshop!
}
