// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Event struct {
	ID string `json:"id"`
}

type NewWorkshop struct {
	ID           string             `json:"id"`
	Instance     string             `json:"instance"`
	WorkshopInfo *WorkshopInfoInput `json:"WorkshopInfo"`
	Starts       time.Time          `json:"Starts"`
	Ends         time.Time          `json:"Ends"`
	EventID      string             `json:"EventID"`
}

type Workshop struct {
	ID           string        `json:"id"`
	Instance     string        `json:"instance"`
	WorkshopInfo *WorkshopInfo `json:"WorkshopInfo"`
	Starts       time.Time     `json:"Starts"`
	Ends         time.Time     `json:"Ends"`
	Event        *Event        `json:"Event"`
}

type WorkshopInfo struct {
	Title        string `json:"Title"`
	Slug         string `json:"Slug"`
	LocationName string `json:"LocationName"`
	LocationURL  string `json:"LocationURL"`
	Couples      bool   `json:"Couples"`
}

type WorkshopInfoInput struct {
	Title        string `json:"Title"`
	Slug         string `json:"Slug"`
	LocationName string `json:"LocationName"`
	LocationURL  string `json:"LocationURL"`
	Couples      bool   `json:"Couples"`
}
