// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	Instances string
	Profiles  string
	Tokens    string
	Users     string
}{
	Instances: "instances",
	Profiles:  "profiles",
	Tokens:    "tokens",
	Users:     "users",
}
