// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package event

import (
	context "context"
	paging "github.com/smartnuance/saas-kit/pkg/lib/paging"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	GetWorkshops(ctx context.Context, in *paging.Paging, opts ...grpc.CallOption) (*WorkshopList, error)
	CreateWorkshop(ctx context.Context, in *Workshop, opts ...grpc.CallOption) (*Workshop, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) GetWorkshops(ctx context.Context, in *paging.Paging, opts ...grpc.CallOption) (*WorkshopList, error) {
	out := new(WorkshopList)
	err := c.cc.Invoke(ctx, "/EventService/GetWorkshops", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CreateWorkshop(ctx context.Context, in *Workshop, opts ...grpc.CallOption) (*Workshop, error) {
	out := new(Workshop)
	err := c.cc.Invoke(ctx, "/EventService/CreateWorkshop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility
type EventServiceServer interface {
	GetWorkshops(context.Context, *paging.Paging) (*WorkshopList, error)
	CreateWorkshop(context.Context, *Workshop) (*Workshop, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (UnimplementedEventServiceServer) GetWorkshops(context.Context, *paging.Paging) (*WorkshopList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkshops not implemented")
}
func (UnimplementedEventServiceServer) CreateWorkshop(context.Context, *Workshop) (*Workshop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkshop not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_GetWorkshops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(paging.Paging)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetWorkshops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EventService/GetWorkshops",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetWorkshops(ctx, req.(*paging.Paging))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CreateWorkshop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Workshop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateWorkshop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EventService/CreateWorkshop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateWorkshop(ctx, req.(*Workshop))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkshops",
			Handler:    _EventService_GetWorkshops_Handler,
		},
		{
			MethodName: "CreateWorkshop",
			Handler:    _EventService_CreateWorkshop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/event.proto",
}
